# fly.toml app configuration file generated for omojadata-project23 on 2025-01-23T13:46:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'omojadata-project23'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
